setting up tabBar and adding icons
jsyrtsov/TheMovieDatabase pull request #1
Opened 2020-02-21 19:26 UTC by jsyrtsov

nothing extra hehe

2020-02-21 20:15 UTC, ismetanin requested changes

2020-02-21 20:15 UTC, ismetanin commented on TheMovieDatabase/Assets.xcassets/iconFeedCopy.imageset/Contents.json
> +{
iconFeedCopy? Кажется что-то тут не так

2020-02-21 20:15 UTC, ismetanin commented on TheMovieDatabase/Assets.xcassets/path13392.imageset/Contents.json
> +      "filename" : "path13392.png",
path13392? 🤨

2020-02-21 20:15 UTC, ismetanin commented on TheMovieDatabase/Base.lproj/Main.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="13122.16" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCo
Опционально: а через код сможешь? Чтобы не все делать в одном сториборде
Подсказка: придется создавать и задавать свой UIWindow в AppDelegate в didFinishLaunching и в Info.plist потереть настройки

2020-02-21 20:25 UTC, jsyrtsov commented on TheMovieDatabase/Assets.xcassets/path13392.imageset/Contents.json
> +      "filename" : "path13392.png",
solved, boss

2020-02-22 17:41 UTC, ismetanin approved these changes
В следующем ПР-е все поправлено

2020-02-24 12:20 UTC, merged