Detailed person view controller (not finished)
jsyrtsov/TheMovieDatabase pull request #10
Opened 2020-04-03 08:26 UTC by jsyrtsov

2020-04-03 11:35 UTC, ismetanin requested changes

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            guard let personVC = storyboard.instantiateViewController(identifier: "PersonViewController")
Давай делать лучше String(describing: PersonViewController.self) так избавимся от так называемых "магических строк"

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            personVC.personId = cast[indexPath.row].id
А почему ты сетишь `personId` после пуша в нав стек? Обычно это делают до

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +// MARK: UICollectionViewDataSource
Лучше делать `// MARK: - Some mark` так добавляется доп разделить в просмотре методов файла

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func loadPerson(personId: Int, completion: @escaping (Person?) -> Void) {
Может заведем `PersonService`? Это кажется уже не связано с фильмами

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/PersonViewController.swift
> +        biography.expandedAttributedLink = NSAttributedString(string: "")
А сворачивать не будем получается?

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        url = URL(string: UrlParts.baseUrl + "person/\(personId)/images")
```
var url = URL(string: UrlParts.baseUrl + "person/\(personId)/images")?.appending("api_key", value: UrlParts.apiKey)
```

Или если не влазит в одну строку - добавить перенос перед `.appending` (отступ после переноса оставить такой какой поставит Xcode)

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        url = URL(string: UrlParts.baseUrl + "person/\(personId)/images")
Или даже можно попробовать `guard let url = URL(string: ...).appending(...)`

2020-04-03 11:35 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        url = URL(string: UrlParts.baseUrl + "person/\(personId)/images")
В других местах тоже посмотри чтобы едино было

2020-04-03 11:47 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            guard let personVC = storyboard.instantiateViewController(identifier: "PersonViewController")
Понял, как и с ячейками сделали

2020-04-03 11:48 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            personVC.personId = cast[indexPath.row].id
Честно говоря не знаю, но я и сам это замечал, исправлю

2020-04-03 11:48 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +// MARK: UICollectionViewDataSource
А я все понять не мог почему у меня разделителя нет!!!

2020-04-03 11:48 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +// MARK: UICollectionViewDataSource
Конечно же скидывал на баги хкода

2020-04-03 11:49 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func loadPerson(personId: Int, completion: @escaping (Person?) -> Void) {
Хмммм. Думаю надо будет разделить да

2020-04-03 11:50 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/PersonViewController.swift
> +        biography.expandedAttributedLink = NSAttributedString(string: "")
Сворачивание не работает в этой сторонней либе. И в эпсторе где эпл использует экспандабл лейбел сворачивания тоже не предусмотрено

2020-04-03 12:00 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +// MARK: UICollectionViewDataSource
Можешь себе сниппетов поставить: https://github.com/ismetanin/XcodeCodeSnippets

2020-04-03 12:25 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        url = URL(string: UrlParts.baseUrl + "person/\(personId)/images")
Прям перед точкой перенос вставлять?

2020-04-03 12:26 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/PersonViewController.swift
> +        biography.expandedAttributedLink = NSAttributedString(string: "")
Возможно сворачивание на новой иос 13.4 у них сломалось, потому что на гитхабе нет никакого упоминания о ее неработоспособности

2020-04-03 13:07 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/PersonViewController.swift
> +        biography.expandedAttributedLink = NSAttributedString(string: "")
А в чем тогда прекол этой проперти?

2020-04-03 15:26 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/PersonViewController.swift
> +        biography.expandedAttributedLink = NSAttributedString(string: "")
Подчищу

2020-04-04 11:39 UTC, ismetanin requested changes

2020-04-04 11:39 UTC, ismetanin commented on TheMovieDatabase/Main Service/PersonLoadingService.swift
> +//
Лучше папку назвать Services

2020-04-04 11:39 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +                ) as? FullPosterViewController
Налево сдвинь, должно стать:
```
guard
    let fullViewVC = storyboard.instantiateViewController(
        withIdentifier: FullPosterViewController.identifier
    ) as? FullPosterViewController
else {
    return
}
```

2020-04-04 11:39 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
> +                                                 for: indexPath) as? MovieTableViewCell
Давай переносы лучше вот так везде делать чтобы было единообразно:
```
let cell = tableView.dequeueReusableCell(
    withIdentifier: MovieTableViewCell.identifier,
    for: indexPath
) as? MovieTableViewCell
```

2020-04-04 13:11 UTC, ismetanin approved these changes

2020-04-04 13:38 UTC, merged