Finish person vc
jsyrtsov/TheMovieDatabase pull request #13
Opened 2020-04-09 13:44 UTC by jsyrtsov

2020-04-09 15:34 UTC, ismetanin requested changes

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovie/View/DetailedMovieViewController.swift
> +        } else if let revenue = detailedMovie?.revenue,
Кажется будет плохо если revenue == nil, обычно делают if let, а потом в else блоке худший случай обрабатывают (в твоем случае подставляем текст что инфа скоро будет)

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/Presenter/PersonPresenter.swift
> +                let self = self
Обычно ставят self на первое место, но обоснования этому у меня нет :)

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/Router/PersonRouter.swift
> +        detailedMovieVC.movieId = movieId
Потом надо переделать на передачу в configure если будем переделывать на мвп

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +class PersonMovieTableViewCell: UITableViewCell {
Марки забыл

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +class PersonMovieTableViewCell: UITableViewCell {
И ещё научу тебя такой штуке: каждому классу по дефолту давай проставлять `final` у классов - это означает что он не должен наследоваться, а если тебе все таки нужно отнаследоваться от класса будет, тогда уберешь.
Зачем?
1) Теоретически уменьшается компайл тайм
2) Сложная тема, но если у тебя `final` класс, то свифт методы вызывает напрямую (static или direct называют), а не через message/table. Если коротко, есть такая штука как диспатчеризация методов, то как язык ищет какой код исполнить когда ты делаешь `someMethod()`. Для более детального изучения посоветую вот тут почитать: https://www.rightpoint.com/rplabs/switch-method-dispatch-table https://trinhngocthuyen.github.io/tech/method-dispatch-in-swift/ https://www.mikeash.com/pyblog/friday-qa-2014-07-04-secrets-of-swifts-speed.html (или по крайней мере отложи в список для почитать на досуге)
3) Прежде чем наследоваться лишний раз задумаешься стоит ли

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +        if let yearStr = personMovie.releaseDate?.prefix(4) {
Может через форматтер? Только статически его тут объяви чтобы не создавать форматтер на каждую ячейку (это может быть дорого)

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +        output?.loadPersonCredits()
Можно сделать просто метод `loadData` например и уже в презентере загружать из двух мест

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +    private func hideToggle() {
Что такое `toggle`? По идее ты тут никакой не тогл скрываешь, подумай над названием

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +        output?.loadPersonCredits()
И давай усложним тебе жизнь: 
Задача такая вызвать `configure(personCast:personCrew:)` только когда оба запроса выполняться, то есть и тот и другой получили данные и тогда только показываем
1) Запросы должны выполняться параллельно, а не один в другом
2) Лучше использовать DispatchGroup

2020-04-09 15:34 UTC, ismetanin commented on TheMovieDatabase/Views/Base.lproj/Main.storyboard
>              <point key="canvasLocation" x="1560.8" y="817.24137931034488"/>
Жду недождусь того момента когда совсем удалим

2020-04-10 07:26 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/Router/PersonRouter.swift
> +        detailedMovieVC.movieId = movieId
как будет время попробую переделать в мвп

2020-04-10 07:26 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/Presenter/PersonPresenter.swift
> +                let self = self
по значимости может)

2020-04-10 07:27 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +class PersonMovieTableViewCell: UITableViewCell {
> Марки забыл

да, в ячейках наверное в некоторых забыл (

2020-04-10 07:28 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +        output?.loadPersonCredits()
> И давай усложним тебе жизнь:
ахахха. а давай))

2020-04-10 07:29 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +    private func hideToggle() {
'toggleHiding()' ?

2020-04-10 07:31 UTC, jsyrtsov commented on TheMovieDatabase/Views/Base.lproj/Main.storyboard
>              <point key="canvasLocation" x="1560.8" y="817.24137931034488"/>
я кстати не знаю как раскидать всю иерархию экранов-вкладок таббара по отдельным сторибордам

2020-04-10 08:33 UTC, ismetanin commented on TheMovieDatabase/Views/Base.lproj/Main.storyboard
>              <point key="canvasLocation" x="1560.8" y="817.24137931034488"/>
Придется задавать начальный экран через AppDelegate
```
func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
) -> Bool {
    initializeRootView()
    return true
}

private func initializeRootView() {
    window = UIWindow(frame: UIScreen.main.bounds)
    window?.rootViewController = UIViewController()
    window?.makeKeyAndVisible()
    applicationCoordinator.start()
}
```

И вот в `window?.rootViewController` надо будет подставить UITabBarController сконфигурированный с твоими контроллерами, то есть где-то ещё в функции создать его, закинуть туда контроллеры в табы и отдать чтобы положить в рут контроллер

2020-04-10 08:34 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/Presenter/PersonPresenter.swift
> +                let self = self
Да просто всегда нужно писать `guard let self`, то есть по дефолту это пишут, а параметры как бы уже позже и не везде

2020-04-10 10:10 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +        if let yearStr = personMovie.releaseDate?.prefix(4) {
да в принципе он наверное не нужен тут раз уж я использую только год, быстрее обрезать строку просто. там где он нужен я его создаю, как раз думал над тем чтобы его отдельно где-то один раз создать и настроить и пользоваться им

2020-04-10 10:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +        if let yearStr = personMovie.releaseDate?.prefix(4) {
Я просто боюсь что произойдет если дата не в том формате придет. А так в целом да

2020-04-10 13:38 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovie/View/DetailedMovieViewController.swift
> +        } else if let revenue = detailedMovie?.revenue,
там присылают либо 0 либо конкретную цифру

поэтому я сравниваю с ноликом в первой ветке ифа

2020-04-10 14:18 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +        if let yearStr = personMovie.releaseDate?.prefix(4) {
дак форматтер не спасет от пришедшей даты не в том формате. он же не поймет как ее пережевывать

2020-04-11 07:03 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/Person/View/Cells/PersonMovieTableViewCell.swift
> +        if let yearStr = personMovie.releaseDate?.prefix(4) {
В целом да, ты прав

2020-04-14 17:32 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/Person/View/PersonViewController.swift
> +        output?.loadPersonCredits()
в итоге усложнили жизнь юзера приложения ))

2020-04-15 06:38 UTC, ismetanin approved these changes

2020-04-15 12:01 UTC, jsyrtsov commented on TheMovieDatabase/Views/Base.lproj/Main.storyboard
>              <point key="canvasLocation" x="1560.8" y="817.24137931034488"/>
> Жду недождусь того момента когда совсем удалим

настал этот день

2020-04-15 12:10 UTC, ismetanin requested changes

2020-04-15 12:10 UTC, ismetanin commented on TheMovieDatabase/AppDelegate.swift
> +        }
Как больно смотреть на эти три загрузки контроллера подряд)
Надо бы это все отрефакторить на конфигураторы как-нибудь...

2020-04-15 12:10 UTC, ismetanin commented on TheMovieDatabase/AppDelegate.swift
> +        tabBarController.tabBar.items?[2].image = #imageLiteral(resourceName: "iconSearch")
Давай сделаем через UITabBarItem-ы
В контролере:
```
tabBarItem = UITabBarItem(title: ..., image: ...)
```

2020-04-15 12:41 UTC, jsyrtsov commented on TheMovieDatabase/AppDelegate.swift
> +        }
хорошо, шэф)

2020-04-15 13:41 UTC, ismetanin approved these changes

2020-04-15 13:44 UTC, merged