added tableView to feedVC and detailVC
jsyrtsov/TheMovieDatabase pull request #2
Opened 2020-02-21 21:16 UTC by jsyrtsov

2020-02-22 08:12 UTC, ismetanin requested changes
И ещё замечание: названия веток можно попроще, эту например я бы назвал в духе: "controllers-setup-and-movie-list-layout", а вообще лучше избегать конечно "and" и герундия
Также и в коммитах - лучше использовать инфинитив, да, это кажется немного глупо с точки зрения языка, но коммит мессадж должен быть четким и понятным

То есть если передлать твои предыдущие можно было бы выразить их так:
"setting up tabBar and adding icons" -> set up tabbar and add icons
"added tableView and few VCs" -> add main view controllers and layout for movie list (few VCs не очень хорошо потому что 1) Сокращение, 2) few не очень конкретно описывает что ты натворил)

2020-02-22 08:12 UTC, ismetanin commented on TheMovieDatabase/Feed/DetailedViewController.swift
> +class DetailedViewController: UIViewController {
Detailed what? Детали чего ты тут будешь показывать? Непонятно :(
`MovieDetailsViewController` в моей голове звучит гораздо понятнее

2020-02-22 08:12 UTC, ismetanin commented on TheMovieDatabase/Feed/FeedViewController.swift
> +        // Do any additional setup after loading the view.
Давай удалять все дефолтные комменты которые создает тебе Xcode, кроме тех что в хедере
Вот как этот и тот что ниже с `MARK: - Navigation`

Почему? Они не несут сейчас никакой нагрузки и никак не облегчают чтение файла (по крайней мере лично мне)

2020-02-22 08:12 UTC, ismetanin commented on TheMovieDatabase/Feed/MovieTableViewCell.swift
> +    override func awakeFromNib() {
А зачем метод реализовывать, который ничего не делает, а просто вызывает super реализацию? 
То есть это никак не влияет на поведение кода и только добавляет лишний (с setSelected такая же ситуация)

2020-02-22 08:12 UTC, ismetanin commented on TheMovieDatabase/Search/SearchViewController.swift
> +class SearchViewController: UIViewController {
А что искать будем?

2020-02-22 17:15 UTC, jsyrtsov commented on TheMovieDatabase/Search/SearchViewController.swift
> +class SearchViewController: UIViewController {
ты намекаешь на изменение названия? добавить что то типа moviesearch ?

2020-02-22 17:40 UTC, ismetanin commented on TheMovieDatabase/Search/SearchViewController.swift
> +class SearchViewController: UIViewController {
Да

2020-02-24 11:47 UTC, ismetanin approved these changes

2020-02-24 12:12 UTC, ismetanin approved these changes

2020-02-24 12:20 UTC, merged