Make search
jsyrtsov/TheMovieDatabase pull request #4
Opened 2020-02-28 09:04 UTC by jsyrtsov

2020-02-28 11:05 UTC, ismetanin requested changes

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesService.swift
> +    var totalPages = 1
`private`

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesService.swift
> +    var totalPages = 1
И проверку `manager.currentPageNum < manager.totalPages` давай делать не в контроллере, а добавим сюда переменную вычисляемую и назовем её к примеру `canLoadMore`

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/SearchService.swift
> +    private let apiKey = "43c76333cdbd2a5869d68050de560ceb"
> DRY - don't repeat yourself

Ты в каждом сервисе собираешься так делать? Давай создадим файл `Constants.swift` в котором зададим enum с названием, например, ServiceConstants/URLConstants, куда сможем перенести этот ключ, базовую часть из URL  (имею ввиду `https://api.themoviedb.org/3/`)

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/SearchService.swift
> +        print(urlString)
🧐

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/SearchService.swift
> +            if let data = data {
Можно заменить на `guard` и дальше будет вложенность меньше

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/Network/SearchService.swift
> +            if let data = data {
И у тебя сейчас получается если `data == nil`, то никакой комплишен не вызовется

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +        loadMovies()
Давай добавим параметр входящий в метод `loadMovies`, будем туда передавать текст, а переменную класса `searchWords` можно будет вообще убрать

Также выставлять текущую страницу неправильно, нужно внутрии сервиса все разруливать, и ты как-то определись, у тебя `manager` или `service` все таки?

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +        if let searchW = searchBar.text {
Что значит `searchW` не очень понятно :(
Может лучше назвать `searchQuery`?

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +            searchWords = replaced
`searchWords = searchW.replacingOccurrences(of: " ", with: "%20")`, но с учетом что эту переменную стоит убрать, я там пониже описал, это уже не понадобится :)

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +            searchWords = replaced
Но трюк запомни, ты просто завел переменную ради этого и сразу её переложил в другю и все, выглядит лишне

2020-02-28 11:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +            }
Вот так делать не очень хорошо, мы сейчас если уберем `currentPageNum` ты вероятно захочешь придумать новый костыль, но давай просто два разных обработчика ответа сделаем, один в `textDidChange`, а другой в `willDisplay`, один будет присваивать новое значение, а другой делать `append`

2020-02-28 11:08 UTC, ismetanin requested changes

2020-02-28 11:08 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesService.swift
> +    var totalPages = 1
Почему проверку лучше не делать в контроллере? Потому что это в очередной раз раскрытие деталей реализации твоего сервиса и твоего сетевого стэка, если ты захочешь из базы грузить у тебя возникнут проблемы с такой проверкой :)

2020-02-29 17:27 UTC, Kibeshev requested changes

2020-02-29 17:27 UTC, Kibeshev commented on TheMovieDatabase/ViewControllers/MovieTableViewCell.swift
> +
Этот код наверно никакой функции не делает

2020-02-29 17:27 UTC, Kibeshev commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +            if self.manager.currentPageNum == 1 {
Мне показалось немного странным название "currentPageNum", а точнее "Num", думаю "Page" и так указывает на то что это будет номер твоей страницы.

2020-03-02 08:29 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
>  class SearchMovieViewController: UIViewController {
А что происходит с поиском когда ты нажимаешь "Cancel" на нем?

2020-03-03 07:14 UTC, ismetanin requested changes

2020-03-03 07:14 UTC, ismetanin commented on TheMovieDatabase/Network/Constants.swift
> +enum urlKeys {
Лучше `URLConstants` key обычно используется в качестве прямого значения "ключ", то есть ожидаешь тут увидеть ключи для какого-нибудь Dictionary например, а тут это не так

2020-03-03 07:14 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
> +        loadMovies()
Параметр добавишь? 😐

2020-03-03 07:14 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/SearchMovieViewController.swift
>              addMovies()
`loadMore` по смыслу больше подходит на мой вкус

2020-03-03 12:12 UTC, ismetanin approved these changes

2020-03-03 13:01 UTC, Kibeshev approved these changes

2020-03-03 13:02 UTC, merged