Realm database
jsyrtsov/TheMovieDatabase pull request #8
Opened 2020-03-14 06:33 UTC by jsyrtsov

2020-03-14 07:53 UTC, ismetanin requested changes

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +let realm = try? Realm()
`private` и внутрь стоража

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +    func saveDetailedMovie(withMovie movie: DetailedMovieObject) {
Немного глупо выглядит вызов с точки зрения языка `storage.saveDetailedMovie(withMovie: movie)` можно первый параметр в таких случаях опускать чтобы вызывать просто `storage.saveDetailedMovie(movie)`

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +        switch isLiked {
```
if isLiked {
    ...
} else {
    ...
}
```

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +        switch isLiked {
Тут тоже свитч убери, булевые переменные всегда через if-else контрукцию проверяют, case когда что-то более сложное с большим количеством вариантов

И тут ещё немного нескладно выглядит: "если лайкнуто - убираем из базы элемент", как-то не этого ожидаешь в коде, а потом уже приходится вглядываться и понимать что ты тут как бы убираешь лайк
Как вариант можно в самом начале функции делать isLiked.toggle(), а потом уже будет прямая логика типа "если лайкнул пишем в базу, нет - удаляем"

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private var isLiked = false
А если я перерисую дизайн и поставлю там звездочку что будешь делать?)
Лучше назвать `isFavorite` на мой вкус, это же все таки избранное, а не как лайки в вк

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private var movieObject: MovieObject?
А я чет не понимаю зачем тебе переменные класса, ты же там их используешь в рамках только одной функции, кажется, значит они тебе тут не нужны

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +                    if movieId == element.id.value {
Лучше guard писать в таких случаях чтобы не увеличивать вложенность

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +                let movieObjects = realm.objects(MovieObject.self)
Можно не все вытаскивать, а сразу нужный через встроенную `filter` в рилме, так должно быть гораздо быстрее и по идее правильнее

`realm.objects(MovieObject.self).filter("id == \(movieId)").first`

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +                let movieObjects = realm.objects(MovieObject.self)
С Detailed также

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +class StorageService {
Тут у тебя будет свалка всех возможных операций добавления? А удаления?

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +class StorageService {
Можно попробовать сделать красиво и по канонам: сделать какой-то общий Storage с общими методами `saveObject`, `removeObject`, то есть не завязываться каждый раз на конкретную модельку, а то у тебя выходит так что ты один и тот же код для разных моделек переписываешь
Также вероятно нужно добавить метод поиска, там похитрее будет, подскажу тебе сигнатуру примерную: `func findObjects(class: Object.Type, query: String) -> [Object] {}` или чтобы не кастить потом Object к твоей модели можно через generic функцию попробовать, заодним разберешься что это такое :) 

А потом добавить методы в сервис типа `func addToFavorites(movie:)`, `func removeFromFavorites(movie:)`  и работать со всеми модельками только через сервис и получать их тоже с сервиса, который будет сам ходить в сторадж, причем получать и отдавать ты будешь не рилм модели, а обычные

Для чего мы все это делаем - чтобы оградить наши контроллеры от знания о модельках рилма и вообще о рилме, так делают чтобы в случае чего его можно было отпилить и заменить на что-то другое с минимальными потерями + в целом размазывать модельки базы по всему приложению "ну такое"

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private func checkLike() {
Сложный вариант, но интереснее:
- Добавить поле isFavorite в модельку (надо только посмотреть как сказать Codable не мапить её из json)
- После того как в сервисе загрузил детальные данные, идти в базу и смотреть нет ли там такого id (тут, кстати, тоже лучше через filter)

Получается можно будет избавиться от поля isFavorite в контроллере и оперировать через поле в модели, но немного глуповато будет смотреться добавление/удаление в таком кейсе

2020-03-14 07:53 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
>  class FavoritesViewController: UIViewController {
Отсюда получается тоже убираем всю явную работу с Realm
Вообще в идеале у тебя только в одном месте должно быть `import RealmSwift` быть - в сторадже

2020-03-14 14:19 UTC, jsyrtsov commented on TheMovieDatabase/Realm/StorageService.swift
> +class StorageService {
хорошая штука эти генерики, однако

2020-03-15 21:37 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +                let movieObjects = realm.objects(MovieObject.self)
спасибо за подсказку про filter, не хватало этого

2020-03-16 14:05 UTC, ismetanin requested changes

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/Models/Movie.swift
> +    //let popularity: Double?
Так ты либо вообще удали, либо раскомментируй
Закомментированный код в девелоп не тащим

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +    func getFavMovies() -> [Movie] {
Смотри, класс называется StorageService, а тут ты спускаешься в детали типа checkLike и getFavMovies
Давай выделим базовый StorageService и ещё один, например, MoviesStorageService и отнаследуем его от базового, и вот в MoviesStorageService уже и будем методы раскрывающие детали писать

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +    func ckeckLike<T>(object: T, id: Int?) -> Bool {
Может что-то в духе isFavorite все таки?

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +class DetailedMovieViewController: UIViewController {
Модельки сохраняешь, удаляешь, а использовать?)

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private func checkLike() {
И название все таки checkLike не очень

2020-03-16 14:05 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +        if storageService.ckeckLike(object: MovieObject.self, id: movieId) {
А тут оно ещё и с опечаткой

2020-03-16 14:20 UTC, jsyrtsov commented on TheMovieDatabase/Realm/StorageService.swift
> +    func ckeckLike<T>(object: T, id: Int?) -> Bool {
сори

2020-03-16 14:23 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +        if storageService.ckeckLike(object: MovieObject.self, id: movieId) {
глазастый

2020-03-16 19:47 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +class DetailedMovieViewController: UIViewController {
теперь использую)) не зря же их несколько дней сижу прикручиваю

2020-03-16 19:49 UTC, jsyrtsov commented on TheMovieDatabase/Models/Movie.swift
> +    //let popularity: Double?
я закомментил, а не удалил, потому что в планах расширить функционал ячейки и отображать в ней кое-что из этого списка

2020-03-17 10:58 UTC, ismetanin requested changes

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Models/Movie.swift
> +    //let popularity: Double?
Ну вот когда будешь расширять тогда добавишь эти строки (поищешь в истории коммитов если что), а сейчас в девелоп лучше не вливать код с комментами, увидит кто - стыд будет :)

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func saveObject<T: Object>(object: T?) {
Кажется ты меня немного не понял когда я говорил про проксирование и все такое. Этот сервис не должен знать про рилм и импортировать его. И эти методы в нем тебе тут не нужны, ты их напрямую не должен вызывать так как ты не должен знать о существовании рилм объектов тут

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    private let storageMoviesService = StorageMoviesService()
Так у тебя же один наследуется от другого, достаточно `storageMoviesService`, кстати, название не очень красиво вышло, если у тебя родитель StorageService, то дочерний класс должен быть `MoviesStorageService`, то есть оригинальное название не разбиваешь

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    // MARK: Network methods
Отступа снизу не хватает

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    // MARK: Network methods
И лучше не указывать явно Network methods, они же тут под капотом и в базу залазят если что)

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
>  class MoviesLoadingService {
Может все таки тогда просто MoviesService? Он тут не только загружает теперь

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func saveObject<T: Object>(object: T?) {
То есть если тебе нужен какой-то метод из стораджа дернуть из твоего контроллера, тебе его надо тут так спроксировать, чтобы ни контроллер, ни этот сервис не узнали о рилме

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func saveObject<T: Object>(object: T?) {
А если метод не используешь, то и не надо никаких проксирований добавлять лишних

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageService.swift
> +    func isFavorite<T>(object: T, id: Int?) -> Bool {
Мне кажется лучше назвать этот метод `contains(object:withId)`, для абстрактного сервиса это как-то понятнее
А если надо, то в дочернем можно будет метод-обертку добавить, который уже будет называться isFavorite

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            favoriteButton.setImage(buttonImage, for: .normal)
А зачем ты это все сохраняешь в переменную, почему нельзя сразу  `favoriteButton.setImage(#нужная картинка#)`

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> -    init(strategy: MoviesServiceLoadingStrategy) {
А убрав пересоздание и передачу стратегии в ините ты пагинацию не сломал? Что будет если поскроллить пару страничек на одном сегменте, переключить в другой и начать скроллить там? Страница пагинации там же будет последняя сохраненная на предыдущем сегменте, не?

2020-03-17 10:58 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageMoviesService.swift
> +    func getFavMovies() -> [Movie] {
Сокращения типа Fav, vc и т.п не очень любят и стараются их избегать

2020-03-17 12:30 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
>  class MoviesLoadingService {
он же у нас всегда загружает. только теперь либо из базы либо из сети, но загружает )

2020-03-17 12:32 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> -    init(strategy: MoviesServiceLoadingStrategy) {
сначала все так и было как ты подметил, но потом я починил это инициализацией сервиса каждый раз при переключении сегментедконтрола

2020-03-19 13:27 UTC, ismetanin requested changes

2020-03-19 13:27 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    func getFavMovies() -> [Movie] {
Как ты любишь сокращения все-таки

2020-03-19 13:27 UTC, ismetanin commented on TheMovieDatabase/Realm/StorageMoviesService.swift
> +class StorageMoviesService: StorageService {
MoviesStorageService, формируем названия по правилу НовыйПрефикс+СтароеНазваниеКласса

2020-03-19 13:31 UTC, ismetanin approved these changes

2020-03-19 13:35 UTC, merged