new cell design
jsyrtsov/TheMovieDatabase pull request #9
Opened 2020-03-20 08:43 UTC by jsyrtsov

2020-03-20 14:11 UTC, ismetanin requested changes

2020-03-20 14:11 UTC, ismetanin commented on TheMovieDatabase/Realm/MoviesStorageService.swift
>      func saveDetailedMovie(detailedMovie: DetailedMovie?) {
Я тут подумал, а смысл здесь опциональный входной параметр делать? Что если я вызову `saveDetailedMovie(detailedMovie: nil)`?

2020-03-20 14:11 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
> +        //tableView.register(UINib(nibName: "MovieTableViewCell", bundle: nil), forCellReuseIdentifier: "moviesCell")
Комментированный код? Может тогда уберем NewMovieTableViewCell и переименуем ее в MovieTableViewCell?

2020-03-20 20:56 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
> +        //tableView.register(UINib(nibName: "MovieTableViewCell", bundle: nil), forCellReuseIdentifier: "moviesCell")
блин сори забыл про него

2020-03-20 20:56 UTC, jsyrtsov commented on TheMovieDatabase/Realm/MoviesStorageService.swift
>      func saveDetailedMovie(detailedMovie: DetailedMovie?) {
чтобы было безопасненько)

2020-03-21 16:59 UTC, ismetanin requested changes

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/Models/CrewEntry.swift
> +struct CrewEntry: Codable {
А почему к этим моделям добавляешь `Entry`, а к остальным не добавлял?

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    private let decoder = JSONDecoder()
В целом мне кажется не обязательно его выносить в проперти, можно создавать прям в методе

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        print(urlNotNil.absoluteString)
😐

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        print(urlNotNil.absoluteString)
В таких случаях проще брейкпоинт поставить и сделать `po myProperty`

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +struct CreditsResponse: Codable {
`private`

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/CastCollectionViewCell.swift
> +    private func configureView() {
Давай писать приватные методы под открытыми

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/CrewCollectionViewCell.swift
> +class CrewCollectionViewCell: UICollectionViewCell {
А думаешь ок две абсолютно идентичные ячейки держать?
Давай одну оставим общую, назовем как-нибудь в духе `PersonCollectionViewCell` или типа того

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            guard let director = self.crew.first(where: { $0.job == "Director" }),
Тебе индекса достаточно чтобы взять элемент, а тут ты делаешь 2 поиска по неотсортированному массиву, то есть 2N, а можно в 1N

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "myCell", for: indexPath) as? MovieTableViewCell
Может идентификатор будем называть также как ячейку?

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/MovieTableViewCell.swift
> +        guard let vote = movie.voteAverage else {
Если тебе vote не придет, у тебя остальные поля не заполнятся тоже, кажется это неправильное поведение

2020-03-21 16:59 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/MovieTableViewCell.swift
> +        } else if vote == 0.0 {
Лишняя ветка, у тебя последний else обрабатывает эту же ситуацию

2020-03-21 17:31 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +            guard let director = self.crew.first(where: { $0.job == "Director" }),
Шаришь

2020-03-21 17:33 UTC, jsyrtsov commented on TheMovieDatabase/Models/CrewEntry.swift
> +struct CrewEntry: Codable {
Добавить ко всем  энтри или у всех убрать энтри?

2020-03-21 17:34 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +    private let decoder = JSONDecoder()
Don’t repeat yourself, bro

2020-03-21 17:36 UTC, jsyrtsov commented on TheMovieDatabase/Network/MoviesLoadingService.swift
> +        print(urlNotNil.absoluteString)
Глазастый

2020-03-21 17:37 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/CrewCollectionViewCell.swift
> +class CrewCollectionViewCell: UICollectionViewCell {
Я бы с радостью да там разные модельки и не получится через одну

2020-03-21 17:38 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/MovieTableViewCell.swift
> +        guard let vote = movie.voteAverage else {
Он всегда приходит, если его нет - придёт 0.0

2020-03-24 13:09 UTC, ismetanin requested changes

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/Models/CrewEntry.swift
> +struct CrewEntry: Codable {
В целом на твой вкус

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/Network/LinkExtractor.swift
> +    let ytd = YoutubeDirectLinkExtractor()
`private` и нормальное название для проперти

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private let personCell = "personCell"
Научу тебя тому как я храню ид ячеек, внутри ячейки создаю статичную проперти
`static let reuseIdentifier = String(describing: MyCell.self)` и потом юзаю в духе `MyCell.reuseIdentifier`

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private let personCell = "personCell"
И использую в качестве ниб нейма и реюз ид

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/FavoritesViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "myCell", for: indexPath) as? MovieTableViewCell
😑

2020-03-24 13:09 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/MovieTableViewCell.swift
> +            }
Кажется я это где-то уже видел, подумай над тем как это написать в одном месте один раз и использовать везде где понадобится

2020-03-24 13:10 UTC, jsyrtsov commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private let personCell = "personCell"
Ценно

2020-03-24 17:06 UTC, ismetanin commented on TheMovieDatabase/ViewControllers/DetailedMovieViewController.swift
> +    private let personCell = "personCell"
Подумал тут, лучше даже не `reuseIdentifier` называть, а просто `identifier` так, кажется, будет логичнее если использовать ещё в нибе

2020-03-25 15:58 UTC, ismetanin approved these changes

2020-03-25 15:58 UTC, ismetanin commented on TheMovieDatabase/Extensions/UIColor.swift
> +    static func colorForVote(vote: Double) -> UIColor {
В свифте стараются не допускать дублирования имени в вызове фунции и писать в соответствии с английским языком, то есть лучше было бы сделать `color(forVote:)`

2020-03-25 20:38 UTC, merged